language: generic
env:
  global:
      # set this to the repo which should have the resulting PDF's
      - GITHUB_REPO="hpcugent/vsc_user_docs"
      # this is an encrypted version of an access token for the repo above.
      # Create it by using the travis tool: travis encrypt -r $GITHUB_REPO GH_TOKEN=<TOKEN>
      # and replace it below
      - secure: 2p42CdapsQR6xkcR/cnqngbwwYqol7QKosxa6n7r4HhKFw7pcaSRWa/5fLOKIunMxW56UfQgTHCecGAU5/oWS8jmEVZYpBThynQBsHBt4xtPw4RUJzAwn6BmWeKX4RHKE6CCcscxAa1Q9vxBWJ0/yRLSP/ikfj6cAH33ga00dFA=
before_install:
    # verify SHA256 checksums to ensure version is bumped when changes are made
    # if this check fails, you should run ./check-version.sh intro-HPC and commit the changes made by the script
    - INTRO_HPC_EXPECTED="20180129.02 4ebebe2492b924760d445adb1230726a49db9754f86b840e676f394f2d43c8b8"
    - ./check-version.sh intro-HPC | grep "Checksum for intro-HPC is still valid"
    - cd $HOME
install:
    - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
    - sudo apt-get install -y --no-install-recommends pgf latexmk
    - pdflatex --version ; latexmk --version
script:
    - cd $TRAVIS_BUILD_DIR
    - make all
after_success:
    - mkdir -p $HOME/build
    - cp -a */*.pdf $HOME/build
    - ls $HOME/build
deploy:
  skip_cleanup: true
  provider: script
  script: $TRAVIS_BUILD_DIR/deploy.sh
  on:
      repo: $GITHUB_REPO
      branch: master
