docs:
  - cloud: mkdocs_cloud.yml
  - linux-tutorial: mkdocs_linux.yml
  - Antwerpen/Linux: mkdocs_Antwerpen_Linux.yml
  - Antwerpen/macOS: mkdocs_Antwerpen_MacOS.yml
  - Antwerpen/Windows: mkdocs_Antwerpen_Windows.yml
  - Gent/Linux: mkdocs_Gent_Linux.yml
  - Gent/macOS: mkdocs_Gent_MacOS.yml
  - Gent/Windows: mkdocs_Gent_Windows.yml
#  - Brussel/Linux
#  - Brussel/MacOS
#  - Brussel/Windows
#  - Leuven/Linux
#  - Leuven/MacOS
#  - Leuven/Windows
os_picks:
  - Antwerpen: mkdocs_Antwerpen_OS_pick.yml
# - Brussel: mkdocs_Brussel_OS_pick.yml
  - Gent: mkdocs_Gent_OS_pick.yml
# - Leuven: mkdocs_Leuven_OS_pick.yml
