site_name: Linux tutorial
docs_dir: docs/linux-tutorial
nav:
  - Getting Started: getting_started.md
  - Navigating: navigating.md
  - Manipulating files and directories: manipulating_files_and_directories.md
  - Uploading/downloading/editing files: uploading_files.md
  - Beyond the basics: beyond_the_basics.md
  - Common Pitfalls: common_pitfalls.md
  - More on the HPC infrastructure: hpc_infrastructure.md

plugins:
  - search
  - include-markdown
  - ugent
  - macros:
      include_yaml:
        - extra/constants.yml
        - extra/gent.yml
  - section-index
  - autorefs
  # - spellcheck
  # - mkdocs-nav-enhancements
  - exclude-search:
      exclude:
        - content/HPC/*
        - content/cloud/*

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - abbr
  - pymdownx.snippets:
      auto_append:
        - ./includes/abbreviations.md
  - toc:
      permalink: "#"
      baselevel: 1
      toc_depth: 3
  - meta
  - tables
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys

theme:
  name: material
  language: en
  features:
    #- navigation.tabs
    - navigation.top
    - navigation.expand
    # - navigation.indexes
    - navigation.tracking
    # - toc.integrate
    - toc.follow
    # - content.tabs.link
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight

extra:
  build_dir: build
